In [1]:
import requests
import pandas as pd
from pyogrio import read_dataframe
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
import glob
import json
import numpy as np
import ee
import geemap as gee
import time
import standardize_pft_funcs as spf
import geopandas as gpd

In [2]:
try:
    ee.Initialize()
except Exception as e:
    print('GEE token expired. Use Jupyter Lab to authenticate')
    ee.Authenticate()

## Load NEON data

In [3]:
# import NEON files
DIR = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021'
FILES = sorted(glob.glob(DIR + '/*Z.csv'))

dfs = []
for file in FILES:
    df = read_dataframe(file)
    dfs.append(df)

## Extract plot centroid coords

In [4]:
# create name column to exract plot centroids
# df = pd.concat(dfs)
# df.reset_index(inplace=True, drop=True)
# df['name'] = df.namedLocation + '.' + df.subplotID

In [5]:
# get subplot lat/lon from server
# requests_dict = {}
# plots = df['name'].to_list()
# url = 'http://data.neonscience.org/api/v0/locations/'
# locs = []

# for plot in plots:
    
#     # only get response when the request is new
#     response = None
#     if plot not in list(requests_dict.keys()):
#         response = requests.get(url + plot)
#         requests_dict[plot] = response
#     else:
#         response = requests_dict[plot]
#     print(url + plot, end='\r')
    
#     # extract lat/lon
#     try:
#         lat = response.json()['data']['locationDecimalLatitude']
#         lon = response.json()['data']['locationDecimalLongitude']
#     except Exception as e:
#         print(response.content)
#         #print(e)
#         lat, lon = None, None
#     locs.append([lat,lon])

In [6]:
# add coordinate data to rows
# coords = pd.DataFrame(locs, columns=['subplot_lat','subplot_lon'])
# df2 = pd.concat([df,coords], axis=1)

In [7]:
# df2.to_csv(DIR + '/NEON.D18.TOOLBARR.DP1.10058.001.div_1m2Data.2021.csv')

## Read NEON plots w/ lat/lon

In [8]:
# set vars
out_path = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021'

In [9]:
# get data
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021/'
f = 'NEON.D18.TOOLBARR.DP1.10058.001.div_1m2Data.2021.csv'
neon = pd.read_csv(p + f, index_col='Unnamed: 0')

In [10]:
neon.columns

Index(['uid', 'namedLocation', 'domainID', 'siteID', 'decimalLatitude',
       'decimalLongitude', 'geodeticDatum', 'coordinateUncertainty',
       'elevation', 'elevationUncertainty', 'plotType', 'nlcdClass', 'plotID',
       'subplotID', 'endDate', 'boutNumber', 'eventID',
       'samplingProtocolVersion', 'divDataType', 'targetTaxaPresent',
       'otherVariablesPresent', 'taxonID', 'scientificName', 'taxonRank',
       'family', 'nativeStatusCode', 'identificationQualifier',
       'taxonIDRemarks', 'morphospeciesID', 'morphospeciesIDRemarks',
       'identificationReferences', 'otherVariables', 'percentCover',
       'heightPlantOver300cm', 'heightPlantSpecies', 'remarks', 'measuredBy',
       'recordedBy', 'samplingImpractical', 'samplingImpracticalRemarks',
       'biophysicalCriteria', 'name', 'subplot_lat', 'subplot_lon'],
      dtype='object')

In [11]:
plant = neon.groupby(['name', 'scientificName']).agg({'percentCover':list})
other = neon.groupby(['name', 'otherVariables']).agg({'percentCover':list})

In [12]:
cover = pd.concat([plant, other], axis=1)
# merge cover columns and drop one
cover.columns = ['pcover_species', 'pcover_other']
cover = cover.where(cover['pcover_species'].notnull(), cover['pcover_other'], axis=0)
cover.drop(columns='pcover_other', inplace=True)
# flatten multi-index
cover.columns = cover.columns.get_level_values(0)
cover = cover.reset_index()
# groupby again
cover.groupby(['name', 'level_1']).agg({'pcover_species':'sum'})
cover.columns = cover.columns.get_level_values(0)
cover = cover.sort_values('name')
cover = cover.reset_index(drop=True)
# sum cover values in list
cover['pcover_species'] = cover['pcover_species'].apply(sum).astype(int)
cover.columns = ['Site Code', 'Name', 'Cover']
cover

                         Site Code                      Name  Cover
0     BARR_001.basePlot.div.31.1.1  Carex aquatilis Wahlenb.      6
1     BARR_001.basePlot.div.31.1.1                      moss     97
2     BARR_001.basePlot.div.31.1.1          otherNonVascular      0
3     BARR_001.basePlot.div.31.1.1                      scat      0
4     BARR_001.basePlot.div.31.1.1    standingDeadHerbaceous     12
...                            ...                       ...    ...
3801  TOOL_043.basePlot.div.41.4.1   Eriophorum vaginatum L.     14
3802  TOOL_043.basePlot.div.41.4.1         Ledum palustre L.     16
3803  TOOL_043.basePlot.div.41.4.1      Rubus chamaemorus L.     37
3804  TOOL_043.basePlot.div.41.4.1    standingDeadHerbaceous     88
3805  TOOL_043.basePlot.div.41.4.1         standingDeadWoody      1

[3806 rows x 3 columns]

In [13]:
species = spf.get_unique_species(DFRAME=neon, 
                                 SCOL='scientificName', 
                                 DNAME='NEON', 
                                 SAVE=True, 
                                 OUTP=out_path)

Saved unique species list to /mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021/NEON_unique_species.csv.

In [14]:
species

                                  scientificName
0                   Alopecurus magellanicus Lam.
1                         Andromeda polifolia L.
2                      Anemone parviflora Michx.
3        Arctagrostis latifolia (R. Br.) Griseb.
4    Arctophila fulva (Trin.) Rupr. ex Andersson
..                                           ...
107             Tofieldia pusilla (Michx.) Pers.
108          Trichophorum cespitosum (L.) Hartm.
109                                Unknown plant
110                      Vaccinium uliginosum L.
111                     Vaccinium vitis-idaea L.

[112 rows x 1 columns]

In [15]:
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021/'
f = 'NEON_ancillary_01.csv'
ancillary = pd.read_csv(p + f, index_col=0)
ancillary

,name,namedLocation,domainID,siteID,geodeticDatum,coordinateUncertainty,elevation,elevationUncertainty,plotType,nlcdClass,plotID,subplotID,endDate,boutNumber,eventID,samplingProtocolVersion,subplot_lat,subplot_lon
0,BARR_001.basePlot.div.31.1.1,BARR_001.basePlot.div,D18,BARR,WGS84,20.10,5.7,0.1,distributed,sedgeHerbaceous,BARR_001,31.1.1,2021-07-19,1,BARR.1.2021,NEON.DOC.014042vL,71.244022,-156.421657
1,BARR_001.basePlot.div.32.2.1,BARR_001.basePlot.div,D18,BARR,WGS84,20.10,5.7,0.1,distributed,sedgeHerbaceous,BARR_001,32.2.1,2021-07-19,1,BARR.1.2021,NEON.DOC.014042vL,71.244021,-156.421132
2,BARR_001.basePlot.div.32.4.1,BARR_001.basePlot.div,D18,BARR,WGS84,20.10,5.7,0.1,distributed,sedgeHerbaceous,BARR_001,32.4.1,2021-07-19,1,BARR.1.2021,NEON.DOC.014042vL,71.244102,-156.421122
3,BARR_001.basePlot.div.40.1.1,BARR_001.basePlot.div,D18,BARR,WGS84,20.10,5.7,0.1,distributed,sedgeHerbaceous,BARR_001,40.1.1,2021-07-19,1,BARR.1.2021,NEON.DOC.014042vL,71.244110,-156.421666
4,BARR_001.basePlot.div.40.3.1,BARR_001.basePlot.div,D18,BARR,WGS84,20.10,5.7,0.1,distributed,sedgeHerbaceous,BARR_001,40.3.1,2021-07-19,1,BARR.1.2021,NEON.DOC.014042vL,71.244191,-156.421656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,TOOL_043.basePlot.div.32.2.1,TOOL_043.basePlot.div,D18,TOOL,WGS84,20.25,821.6,0.2,tower,sedgeHerbaceous,TOOL_043,32.2.1,8/6/21,1,TOOL.1.2021,NEON.DOC.014042vL,68.665429,-149.375293
276,TOOL_043.basePlot.div.32.4.1,TOOL_043.basePlot.div,D18,TOOL,WGS84,20.25,821.6,0.2,tower,sedgeHerbaceous,TOOL_043,32.4.1,8/6/21,1,TOOL.1.2021,NEON.DOC.014042vL,68.665510,-149.375301
277,TOOL_043.basePlot.div.40.1.1,TOOL_043.basePlot.div,D18,TOOL,WGS84,20.25,821.6,0.2,tower,sedgeHerbaceous,TOOL_043,40.1.1,8/6/21,1,TOOL.1.2021,NEON.DOC.014042vL,68.665518,-149.375736
278,TOOL_043.basePlot.div.40.3.1,TOOL_043.basePlot.div,D18,TOOL,WGS84,20.25,821.6,0.2,tower,sedgeHerbaceous,TOOL_043,40.3.1,8/6/21,1,TOOL.1.2021,NEON.DOC.014042vL,68.665599,-149.375744
279,TOOL_043.basePlot.div.41.4.1,TOOL_043.basePlot.div,D18,TOOL,WGS84,20.25,821.6,0.2,tower,sedgeHerbaceous,TOOL_043,41.4.1,8/6/21,1,TOOL.1.2021,NEON.DOC.014042vL,68.665598,-149.375283

In [16]:
# load species checklist
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/AKVEG_ACCS/'
f = 'AKVEG_species_checklist.csv'
checklist = read_dataframe(p + f)

# get first 2 words (genus-species) from checklist accepted name and data species name
checklist['Mapping Name'] = checklist['Accepted Name'].apply(spf.get_substrings)
species['Mapping Name'] = species['scientificName'].apply(spf.get_substrings)

In [17]:
habits = spf.fill_habits(unique_species=species, 
                         checklist=checklist, 
                         u_name='scientificName', 
                         c_unofficial_name='Name', 
                         c_official_name='Accepted Name', 
                         mapping_name='Mapping Name',
                         habit='Habit')

38 species are missing habits.
15 species still missing habits.
4 species still missing habits.
3 species still missing habits.

In [18]:
habits

,Name,Mapping Name,Habit
index,,,
0,Alopecurus magellanicus Lam.,Alopecurus magellanicus,graminoid
1,Andromeda polifolia L.,Andromeda polifolia,dwarf shrub
2,Anemone parviflora Michx.,Anemone parviflora,forb
3,Arctagrostis latifolia (R. Br.) Griseb.,Arctagrostis latifolia,graminoid
4,Arctophila fulva (Trin.) Rupr. ex Andersson,Arctophila fulva,graminoid
...,...,...,...
107,Tofieldia pusilla (Michx.) Pers.,Tofieldia pusilla,forb
108,Trichophorum cespitosum (L.) Hartm.,Trichophorum cespitosum,graminoid
109,Unknown plant,plant,NaN
110,Vaccinium uliginosum L.,Vaccinium uliginosum,"shrub,dwarf shrub"
111,Vaccinium vitis-idaea L.,Vaccinium vitis-idaea,dwarf shrub

## Add evergreen/deciduous distinctions from macander 22 supplementary

In [19]:
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/AK-AVA_post2000/'
f = 'evergreendecid_macander2022.csv'
evergrndecid = pd.read_csv(p + f, header=None)
evergrndecid.columns = ['evergreendecid', 'species']
final = spf.add_leaf_habit(habits, evergrndecid)

In [20]:
final

,Name,Mapping Name,Potential Habit,Habit,Leaf Retention,Potential Height,Height
index,,,,,,,
0,Alopecurus magellanicus Lam.,Alopecurus magellanicus,graminoid,graminoid,,NaN,NaN
1,Andromeda polifolia L.,Andromeda polifolia,dwarf shrub,dwarf shrub,Evergreen,NaN,NaN
2,Anemone parviflora Michx.,Anemone parviflora,forb,forb,,NaN,NaN
3,Arctagrostis latifolia (R. Br.) Griseb.,Arctagrostis latifolia,graminoid,graminoid,,NaN,NaN
4,Arctophila fulva (Trin.) Rupr. ex Andersson,Arctophila fulva,graminoid,graminoid,,NaN,NaN
...,...,...,...,...,...,...,...
107,Tofieldia pusilla (Michx.) Pers.,Tofieldia pusilla,forb,forb,,NaN,NaN
108,Trichophorum cespitosum (L.) Hartm.,Trichophorum cespitosum,graminoid,graminoid,,NaN,NaN
109,Unknown plant,plant,NaN,NaN,,NaN,NaN
110,Vaccinium uliginosum L.,Vaccinium uliginosum,"shrub,dwarf shrub","shrub,dwarf shrub","Evergreen,Deciduous",NaN,NaN
111,Vaccinium vitis-idaea L.,Vaccinium vitis-idaea,dwarf shrub,dwarf shrub,"Evergreen,Deciduous",NaN,NaN

In [21]:
# export
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021/'
f = 'NEON_species_habit_00.csv'
final.to_csv(p + f)

In [22]:
list(final['Potential Habit'].unique())

['graminoid',
 'dwarf shrub',
 'forb',
 ' shrub, dwarf shrub, tree,deciduous tree, deciduous tree',
 nan,
 'spore-bearing',
 ' shrub,dwarf shrub',
 'shrub',
 ' shrub, dwarf shrub, tree,dwarf shrub, deciduous tree']

## Export shrubs, nonshrubs, and null

In [23]:
# get all shrub species
finalnonnull = final[~final['Potential Habit'].isnull()]
shrubs = finalnonnull[finalnonnull['Potential Habit'].str.contains('shrub')]
shrubs.to_csv(p + 'NEON_shrubs_00.csv')

In [24]:
# get all non-shrub species
nonshrubs = finalnonnull[~finalnonnull['Potential Habit'].str.contains('shrub')]
nonshrubs.to_csv(p + 'NEON_nonshrubs_00.csv')

In [25]:
# get null habits
finalnull = final[final['Potential Habit'].isnull()]
finalnull.to_csv(p + 'NEON_nullhabit_00.csv')

In [26]:
len(finalnull) + len(nonshrubs) + len(shrubs)

112

In [27]:
len(final)

112

## HERE: Manually add data from Amy's shrub03 file

## Standardize PFT Schema

In [28]:
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021/'
nonshrub = 'NEON_nonshrubs_00.csv'
shrub = 'NEON_shrubs_01.csv'
null = 'NEON_nullhabit_01.csv'
alltypes = [nonshrub, shrub, null]

d = []
for t in alltypes:
    habits = pd.read_csv(p + t, index_col=0)
    d.append(habits)

In [29]:
completehabits = pd.concat(d)
completehabits['Habit'].unique()

array(['graminoid', 'forb', 'spore-bearing', 'dwarf shrub', 'shrub',
       'unknown', 'lichen', 'litter', 'moss', 'other', 'fungus', 'rock',
       'scat', 'soil', 'dead herbaceous', 'dead woody', 'water'],
      dtype=object)

In [30]:
def standardize_habit_nonstandard(habitrow, leafrow, heightrow):
    
    habitrow = habitrow.to_numpy()
    leafrow = leafrow.to_numpy()
    heightrow = heightrow.to_numpy()
    new_row = []
    
    for habit, leaf, height in zip(habitrow, leafrow, heightrow):
        habit = habit.lower()
        if habit == 'shrub, tree':
            new_habit = f'{leaf} dwarf to tree cover (%)'
        elif habit == 'dwarf shrub':
            new_habit = f'{leaf} {habit} cover (%)'
        elif 'shrub' in habit:
            new_habit = f'{leaf} {height} cover (%)'
        else:
            new_habit = f'{habit} cover (%)'
        new_row.append(" ".join(new_habit.split()).lower())
    
    return new_row

In [31]:
def standardize_habit(habitrow, leafrow, heightrow):
    
    habitrow = habitrow.to_numpy()
    leafrow = leafrow.to_numpy()
    heightrow = heightrow.to_numpy()
    new_row = []
    
    for habit, leaf, height in zip(habitrow, leafrow, heightrow):
        habit = habit.lower()
        if 'algae' in habit:
            new_habit = 'lichen cover (%)'
        elif habit == np.nan or 'unknown' in habit:
            new_habit = 'unknown cover (%)'
        elif 'moss' in habit or 'liverwort' in habit:
            new_habit = 'bryophyte cover (%)'
        elif 'spore-bearing' in habit:
            new_habit = 'forb cover (%)'
        elif habit == 'grass':
            new_habit = 'graminoid cover (%)'
            
        elif habit == 'shrub, tree':
            new_habit = f'{leaf} dwarf to tree cover (%)'
        elif habit == 'dwarf shrub':
            new_habit = f'{leaf} {habit} cover (%)'
        elif 'shrub' in habit:
            new_habit = f'{leaf} {height} cover (%)'
            
        elif 'litter' in habit or 'scat' in habit:
            new_habit = 'litter cover (%)'
        elif 'soil' in habit or 'rock' in habit:
            new_habit = 'bare ground cover (%)'
            
        else:
            new_habit = f'{habit} cover (%)'
        new_row.append(" ".join(new_habit.split()).lower())
    
    return new_row

In [32]:
# standardized PFT
standard_habit_col = standardize_habit(completehabits['Habit'], 
                                       completehabits['Leaf Retention'], 
                                       completehabits['Height'])

In [33]:
# non-standardized PFT
nonstandard_habit_col = standardize_habit_nonstandard(completehabits['Habit'], 
                                                      completehabits['Leaf Retention'],
                                                      completehabits['Height'])

In [34]:
completehabits['Standard Habit'] = standard_habit_col
completehabits['NonStandard Habit'] = nonstandard_habit_col

In [35]:
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/NEON_2021/'
f = 'NEON_species_habit_standardized.csv'
completehabits.to_csv(p + f)

In [36]:
standard_fcover = completehabits.drop(columns=['NonStandard Habit'])
nonstandard_fcover = completehabits.drop(columns='NonStandard Habit')

## Join habit to fcover data

In [37]:
# add vegetation fcover and sum to PFT level
def add_cover(cover_df, pft_groups, habit_col):
    #cover = cover_df.reset_index()
    withfcover = cover.merge(pft_groups, left_on='Name', right_on='Name', how='left')
    grouped = withfcover.groupby(['Site Code', habit_col], 
                                 group_keys=True).agg({'Cover': 'sum'})
    return grouped

In [38]:
# flatten multilevel
def flatten_multilevel(grouped):
    grouped.columns = grouped.columns.get_level_values(0)
    grouped = grouped.reset_index()
    return grouped

In [39]:
# transpose
def transpose_df(grouped, habit_col):
    groups = grouped.set_index(['Site Code', habit_col]).stack().unstack([1,2])
    groups.columns = groups.columns.get_level_values(0)
    groups = groups.reset_index()
    return groups

In [40]:
def add_standard_cols(groups):
    
    # required columns
    necessary_cols = ['deciduous dwarf shrub cover (%)',
                      'deciduous dwarf to low shrub cover (%)',
                      'deciduous dwarf to tall shrub cover (%)',
                      'deciduous dwarf to tree cover (%)',
                      'deciduous tree cover (%)',
                      'evergreen dwarf shrub cover (%)',
                      'evergreen dwarf to low shrub cover (%)',
                      'evergreen dwarf to tall shrub cover (%)',
                      'evergreen dwarf to tree cover (%)',
                      'evergreen tree cover (%)',
                      'bryophyte cover (%)',
                      'forb cover (%)',
                      'graminoid cover (%)',
                      'lichen cover (%)']
    
    # add missing columns and fill with nan
    cols = groups.columns.tolist()
    addcols = []
    for nc in necessary_cols:
        if nc not in cols:
            addcols.append(nc)
    groups[addcols] = np.nan
    return groups

In [41]:
grouped_standard = add_cover(cover, completehabits, 'Standard Habit')
grouped_standard = flatten_multilevel(grouped_standard)
grouped_standard = transpose_df(grouped_standard, 'Standard Habit')
standard_groups = add_standard_cols(grouped_standard)

In [42]:
grouped_nonstand = add_cover(cover, completehabits, 'NonStandard Habit')
grouped_nonstand = flatten_multilevel(grouped_nonstand)
grouped_nonstand = transpose_df(grouped_nonstand, 'NonStandard Habit')

## Read ancillary table

In [43]:
anc = ancillary.copy()
# year
anc['year'] = pd.DatetimeIndex(anc['endDate']).year
anc['year'] = anc['year'].astype('int')
# plot size
anc['plot_radius_m'] = 1
# dataset source
anc['source'] = 'NEON'
anc.rename(columns={'subplot_lat':'latitude','subplot_lon':'longitude'}, inplace=True)

In [44]:
anc = anc[['name', 'latitude', 'longitude', 'year', 'plot_radius_m', 'source']]

In [45]:
anc.rename(columns={'name':'Site Code'}, inplace=True)
anc.set_index('Site Code', inplace=True)

In [46]:
anc

,latitude,longitude,year,plot_radius_m,source
Site Code,,,,,
BARR_001.basePlot.div.31.1.1,71.244022,-156.421657,2021,1,NEON
BARR_001.basePlot.div.32.2.1,71.244021,-156.421132,2021,1,NEON
BARR_001.basePlot.div.32.4.1,71.244102,-156.421122,2021,1,NEON
BARR_001.basePlot.div.40.1.1,71.244110,-156.421666,2021,1,NEON
BARR_001.basePlot.div.40.3.1,71.244191,-156.421656,2021,1,NEON
...,...,...,...,...,...
TOOL_043.basePlot.div.32.2.1,68.665429,-149.375293,2021,1,NEON
TOOL_043.basePlot.div.32.4.1,68.665510,-149.375301,2021,1,NEON
TOOL_043.basePlot.div.40.1.1,68.665518,-149.375736,2021,1,NEON
TOOL_043.basePlot.div.40.3.1,68.665599,-149.375744,2021,1,NEON
TOOL_043.basePlot.div.41.4.1,68.665598,-149.375283,2021,1,NEON

## Create total cover file (not merged)

In [47]:
# set index and sort columns
totcover_nm = grouped_nonstand.copy()
totcover_nm.set_index('Site Code', inplace=True)
totcover_nm.drop(columns=['fungus cover (%)'], inplace=True)
totcover_nm.columns.name = None
totcover_nm = totcover_nm[sorted(totcover_nm.columns.tolist())]

In [48]:
# add "total cover" to column names
cols = totcover_nm.columns.tolist()
cols = [x.replace('cover (%)' , 'total cover (%)') for x in cols]
totcover_nm.columns = cols

In [49]:
# add ancillary
totcover_nm.index = totcover_nm.index.astype(str)
anc.index = anc.index.astype(str)
totcover_nm = pd.concat([totcover_nm, anc], axis=1, join='inner')
totcover_nm.replace(0.0, np.NaN, inplace=True)
totcover_nm.index.name = 'Site Code'

In [50]:
# combine cover columns
totcover_nm.drop(columns=['other total cover (%)', 
                          'unknown total cover (%)'], inplace=True)
totcover_nm = totcover_nm[totcover_nm['water total cover (%)'] != 100]

In [51]:
# export
p = '/mnt/poseidon/remotesensing/arctic/data/training/Test_04/original_files/'
f = 'NEON_fcover_total_orig.csv'
totcover_nm.to_csv(p + f)

In [52]:
len(totcover_nm)

275

## Create total cover file (merged)

In [53]:
# set index and sort columns
totcover = standard_groups.copy()
totcover.set_index('Site Code', inplace=True)
totcover.drop(columns=['fungus cover (%)'], inplace=True)
totcover.columns.name = None
totcover = totcover[sorted(totcover.columns.tolist())]

In [54]:
# add "total cover" to column names
cols = totcover.columns.tolist()
cols = [x.replace('cover (%)' , 'total cover (%)') for x in cols]
totcover.columns = cols

In [55]:
# add ancillary
totcover.index = totcover.index.astype(str)
anc.index = anc.index.astype(str)
totcover = pd.concat([totcover, anc], axis=1, join='inner')
totcover.replace(0.0, np.NaN, inplace=True)
totcover.index.name = 'Site Code'

In [56]:
# combine cover columns
totcover.drop(columns=['other total cover (%)', 
                       'unknown total cover (%)'], inplace=True)
totcover = totcover[totcover['water total cover (%)'] != 100]

In [57]:
# export
p = '/mnt/poseidon/remotesensing/arctic/data/training/Test_04/original_files/'
f = 'NEON_fcover_total_merged.csv'
totcover.to_csv(p + f)

## Aggregate child plots to parent plots

In [58]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [59]:
# load the plots of interest
p = '/mnt/poseidon/remotesensing/arctic/data/training/Test_04/original_files/'
f = 'NEON_fcover_total_merged.csv'
akava = pd.read_csv(p + f)

# only plots with very small sizes need to be processed, 
# the other remains the same, discarding all plots earlier than 2010
akava['plot_radius_m'].astype(float)
akava_small_fcover = akava[(akava['plot_radius_m']<10) &  (akava['year']>=2010)]
akava_large_fcover = akava[(akava['plot_radius_m']>=10) &  (akava['year']>=2010)]

In [60]:
len(akava_small_fcover)

275

In [61]:
selected_columns = ['Site Code','year','latitude', 'longitude', 'source']
akava_small = akava_small_fcover[selected_columns]
# akava_small = akava.fillna(0)
akava_small.head()

                      Site Code  year   latitude   longitude source
0  BARR_001.basePlot.div.31.1.1  2021  71.244022 -156.421657   NEON
1  BARR_001.basePlot.div.32.2.1  2021  71.244021 -156.421132   NEON
2  BARR_001.basePlot.div.32.4.1  2021  71.244102 -156.421122   NEON
3  BARR_001.basePlot.div.40.1.1  2021  71.244110 -156.421666   NEON
4  BARR_001.basePlot.div.40.3.1  2021  71.244191 -156.421656   NEON

In [62]:
#### transform geographic to utm so that distance caculation is more intuitive
from pyproj import Transformer
src_crs = "EPSG:4326"
target_crs = "EPSG:32606"
transformer = Transformer.from_crs(src_crs, target_crs)

lon = akava_small['longitude'].to_numpy()
lat = akava_small['latitude'].to_numpy()

#### store the projected coords
projcoords = []   
for i in range(0,akava_small.shape[0]):
    xcoord, ycoord = lon[i],lat[i]
    projcoords.append(transformer.transform(ycoord,xcoord))

In [63]:
#### calculate the distance matrix of all small plots (for examination)
from scipy.spatial.distance import cdist
coord = np.array(projcoords)
dist_mat = cdist(coord, coord, 'euclidean')
# dist_mat[:3,:] <= 60

In [64]:
### group pixels/plots based on their euclidean distance
def group_pixels_by_distance(pixel_data, distance_threshold):
    """
        pixel_data: ndarray of coordinate pair: n by 2, default is utm projection
        distance_threshold: threshold used for grouping, default is 60m
        
        return:
        a list of values indicating the group id of each pixel
    
    """
    cluster_id = 0
    pixel_clusters = {}
   
    def expand_cluster(pixel, cluster_id):
        if pixel_clusters.get(cluster_id) is None:
            pixel_clusters[cluster_id] = []
       
        pixel_clusters[cluster_id].append(pixel)

    cluster_array = np.full(len(pixel_data), -1)  # Initialize with -1 (unassigned)
   
    for i, pixel in enumerate(pixel_data):
        assigned = False
       
        for c_id, cluster_pixels in pixel_clusters.items():
            cluster_pixels = np.array(cluster_pixels)
            distances = np.linalg.norm(cluster_pixels - pixel, axis=1)
            if np.any(distances <= distance_threshold):
                expand_cluster(pixel, c_id)
                assigned = True
                cluster_array[i] = c_id
                break
       
        if not assigned:
            expand_cluster(pixel, cluster_id)
            cluster_array[i] = cluster_id
            cluster_id += 1

    return cluster_array

dist_thres = 55
coord = np.array(projcoords)  ## UTM coords, unit is meter
group = group_pixels_by_distance(coord, dist_thres)

In [65]:
### add the group id to df for aggregation
akava_small['group_id'] = group
akava_small.head()

                      Site Code  year   latitude   longitude source  group_id
0  BARR_001.basePlot.div.31.1.1  2021  71.244022 -156.421657   NEON         0
1  BARR_001.basePlot.div.32.2.1  2021  71.244021 -156.421132   NEON         0
2  BARR_001.basePlot.div.32.4.1  2021  71.244102 -156.421122   NEON         0
3  BARR_001.basePlot.div.40.1.1  2021  71.244110 -156.421666   NEON         0
4  BARR_001.basePlot.div.40.3.1  2021  71.244191 -156.421656   NEON         0

In [66]:
groups = akava_small.groupby(['group_id', 
                              'year', 'source']).agg({'latitude':'mean',
                                            'longitude':'mean',
                                            'Site Code':list})

In [67]:
groups2 = groups.explode('Site Code')

In [68]:
groups2.reset_index(inplace=True)
groups2['parent_id'] = (groups2['group_id'].astype(str) + '_' + 
                        groups2['year'].astype(str) + '_' +
                        groups2['source'])
groups2.rename(columns={'latitude':'parent_latitude',
                        'longitude':'parent_longitude'},
               inplace=True)
groups2.drop(columns=['group_id', 'year', 'source'], inplace=True)

In [69]:
groups2.set_index('Site Code', inplace=True)
akava_small_fcover.set_index('Site Code', inplace=True)

In [70]:
joined = pd.concat([akava_small_fcover, groups2], axis=1)
joined.reset_index(inplace=True,)

In [71]:
joined.columns

Index(['Site Code', 'bare ground total cover (%)', 'bryophyte total cover (%)',
       'dead herbaceous total cover (%)', 'dead woody total cover (%)',
       'deciduous dwarf shrub total cover (%)',
       'deciduous dwarf to low shrub total cover (%)',
       'deciduous dwarf to tall shrub total cover (%)',
       'deciduous dwarf to tree total cover (%)',
       'deciduous tree total cover (%)',
       'evergreen dwarf shrub total cover (%)',
       'evergreen dwarf to low shrub total cover (%)',
       'evergreen dwarf to tall shrub total cover (%)',
       'evergreen dwarf to tree total cover (%)',
       'evergreen tree total cover (%)', 'forb total cover (%)',
       'graminoid total cover (%)', 'lichen total cover (%)',
       'litter total cover (%)', 'water total cover (%)', 'latitude',
       'longitude', 'year', 'plot_radius_m', 'source', 'parent_latitude',
       'parent_longitude', 'parent_id'],
      dtype='object')

In [72]:
info_cols = ['parent_latitude', 'parent_longitude']
data_cols = [col for col in joined.columns if 'cover (%)' in col]
anci_cols = set(joined.columns) - set(data_cols) - set(info_cols)
info_dict = dict.fromkeys(info_cols, 'mean')
data_dict = dict.fromkeys(data_cols, 'mean')
anci_dict = dict.fromkeys(anci_cols, set)
d = {**data_dict, **info_dict, **anci_dict}

parent_plots = joined.groupby('parent_id').agg(d)

In [73]:
parent_plots.drop(columns=['latitude', 'longitude', 'parent_id', 
                           'source', 'plot_radius_m'],
                 inplace=True)

In [74]:
parent_plots['year'] = parent_plots['year'].explode()
parent_plots['source'] = 'NEON'
parent_plots.rename(columns={'Site Code':'child_site_codes',
                             'parent_longitude':'longitude',
                             'parent_latitude':'latitude'}, 
                    inplace=True)
parent_plots.index.name = 'Site Code'

In [75]:
parent_plots

,bare ground total cover (%),bryophyte total cover (%),dead herbaceous total cover (%),dead woody total cover (%),deciduous dwarf shrub total cover (%),deciduous dwarf to low shrub total cover (%),deciduous dwarf to tall shrub total cover (%),deciduous dwarf to tree total cover (%),deciduous tree total cover (%),evergreen dwarf shrub total cover (%),...,forb total cover (%),graminoid total cover (%),lichen total cover (%),litter total cover (%),water total cover (%),latitude,longitude,year,child_site_codes,source
Site Code,,,,,,,,,,,,,,,,,,,,,
0_2021_NEON,NaN,73.833333,10.000000,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,...,3.500000,9.333333,1.000000,27.500000,1.000000,71.244106,-156.421395,2021,"{BARR_001.basePlot.div.41.4.1, BARR_001.basePl...",NEON
10_2021_NEON,9.500000,44.166667,10.600000,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,...,25.400000,10.833333,13.000000,17.666667,3.000000,71.253775,-156.380753,2021,"{BARR_012.basePlot.div.40.3.1, BARR_012.basePl...",NEON
11_2021_NEON,NaN,74.333333,9.800000,NaN,6.400000,NaN,NaN,NaN,NaN,NaN,...,7.333333,7.200000,7.200000,22.800000,NaN,71.265929,-156.606090,2021,"{BARR_013.basePlot.div.40.3.1, BARR_013.basePl...",NEON
12_2021_NEON,NaN,96.000000,5.750000,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,...,3.500000,6.750000,3.000000,8.250000,1.000000,71.298787,-156.648069,2021,"{BARR_014.basePlot.div.40.3.1, BARR_014.basePl...",NEON
13_2021_NEON,NaN,87.000000,11.833333,NaN,2.000000,NaN,2.000000,NaN,NaN,NaN,...,NaN,8.333333,6.666667,13.000000,NaN,71.267254,-156.562378,2021,"{BARR_015.basePlot.div.32.4.1, BARR_015.basePl...",NEON
14_2021_NEON,6.500000,37.833333,29.000000,NaN,NaN,NaN,11.000000,NaN,NaN,NaN,...,2.333333,12.333333,6.000000,30.166667,21.000000,71.246041,-156.504816,2021,"{BARR_016.basePlot.div.32.2.1, BARR_016.basePl...",NEON
15_2021_NEON,1.000000,69.833333,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.400000,11.166667,3.400000,28.000000,NaN,71.244828,-156.434660,2021,"{BARR_017.basePlot.div.40.3.1, BARR_017.basePl...",NEON
16_2021_NEON,NaN,97.000000,2.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.750000,9.833333,NaN,3.750000,6.000000,71.306721,-156.616993,2021,"{BARR_018.basePlot.div.41.4.1, BARR_018.basePl...",NEON
17_2021_NEON,NaN,78.333333,7.500000,NaN,3.000000,NaN,7.666667,NaN,NaN,NaN,...,3.000000,6.000000,10.500000,55.000000,32.666667,71.226668,-156.546572,2021,"{BARR_019.basePlot.div.40.1.1, BARR_019.basePl...",NEON
18_2021_NEON,1.000000,76.666667,7.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.666667,16.666667,NaN,14.500000,34.000000,71.261167,-156.489465,2021,"{BARR_020.basePlot.div.32.4.1, BARR_020.basePl...",NEON
19_2021_NEON,NaN,97.000000,4.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.000000,7.333333,NaN,4.333333,NaN,71.255800,-156.550398,2021,"{BARR_021.basePlot.div.32.4.1, BARR_021.basePl...",NEON
1_2021_NEON,NaN,64.666667,13.400000,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,...,2.666667,10.500000,21.666667,14.666667,75.000000,71.273925,-156.599234,2021,"{BARR_002.basePlot.div.32.2.1, BARR_002.basePl...",NEON
20_2021_NEON,NaN,66.666667,9.000000,1.000000,1.000000,NaN,16.000000,NaN,NaN,NaN,...,5.000000,16.000000,NaN,36.166667,53.000000,71.246709,-156.395110,2021,"{BARR_022.basePlot.div.40.1.1, BARR_022.basePl...",NEON
21_2021_NEON,NaN,94.250000,8.000000,NaN,7.500000,NaN,4.000000,NaN,NaN,NaN,...,5.250000,6.500000,6.500000,4.750000,NaN,71.238541,-156.332481,2021,"{BARR_023.basePlot.div.32.4.1, BARR_023.basePl...",NEON
22_2021_NEON,NaN,81.666667,8.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,11.000000,2.000000,13.000000,38.500000,71.306199,-156.639764,2021,"{BARR_024.basePlot.div.41.4.1, BARR_024.basePl...",NEON
23_2021_NEON,NaN,72.200000,6.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.000000,6.800000,7.000000,16.200000,NaN,71.261694,-156.550460,2021,"{BARR_025.basePlot.div.32.4.1, BARR_025.basePl...",NEON
24_2021_NEON,NaN,45.600000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,13.500000,NaN,14.000000,71.400000,71.268656,-156.650980,2021,"{BARR_026.basePlot.div.32.2.1, BARR_026.basePl...",NEON
25_2021_NEON,NaN,98.833333,3.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.833333,3.000000,2.400000,NaN,71.316716,-156.620807,2021,"{BARR_027.basePlot.div.40.3.1, BARR_027.basePl...",NEON
26_2021_NEON,NaN,75.200000,8.500000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,...,3.000000,9.000000,17.333333,35.000000,9.500000,71.250115,-156.527701,2021,"{BARR_028.basePlot.div.32.2.1, BARR_028.basePl...",NEON
27_2021_NEON,4.000000,65.666667,6.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.833333,5.750000,31.166667,4.666667,71.238736,-156.421237,2021,"{BARR_029.basePlot.div.32.2.1, BARR_029.basePl...",NEON
28_2021_NEON,NaN,86.166667,9.333333,NaN,4.333333,NaN,NaN,NaN,NaN,NaN,...,9.400000,11.500000,12.500000,11.166667,NaN,71.247981,-156.430059,2021,"{BARR_030.basePlot.div.32.4.1, BARR_030.basePl...",NEON
29_2021_NEON,NaN,91.666667,5.833333,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,...,5.500000,7.833333,5.250000,7.166667,NaN,71.257797,-156.539290,2021,"{BARR_032.basePlot.div.40.3.1, BARR_032.basePl...",NEON
2_2021_NEON,NaN,89.666667,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.000000,NaN,11.000000,3.000000,71.258670,-156.648849,2021,"{BARR_003.basePlot.div.40.3.1, BARR_003.basePl...",NEON
30_2021_NEON,6.000000,51.166667,6.666667,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,...,9.333333,6.833333,11.750000,28.833333,4.500000,71.285602,-156.607886,2021,"{BARR_051.basePlot.div.41.4.1, BARR_051.basePl...",NEON
31_2021_NEON,NaN,75.666667,8.833333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.333333,4.666667,24.166667,NaN,71.281337,-156.603651,2021,"{BARR_052.basePlot.div.31.1.1, BARR_052.basePl...",NEON
32_2021_NEON,NaN,84.333333,14.833333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,9.400000,3.000000,17.000000,NaN,71.285301,-156.605383,2021,"{BARR_053.basePlot.div.40.1.1, BARR_053.basePl...",NEON
33_2021_NEON,NaN,87.000000,12.500000,NaN,1.000000,5.000000,7.833333,NaN,NaN,16.333333,...,11.500000,13.333333,3.000000,11.000000,4.000000,68.585776,-149.543167,2021,"{TOOL_001.basePlot.div.40.3.1, TOOL_001.basePl...",NEON
34_2021_NEON,NaN,78.333333,11.666667,1.000000,NaN,4.750000,19.000000,NaN,NaN,7.666667,...,4.200000,10.166667,1.500000,11.000000,NaN,68.627945,-149.347226,2021,"{TOOL_002.basePlot.div.40.3.1, TOOL_002.basePl...",NEON
35_2021_NEON,NaN,65.500000,16.833333,1.000000,1.500000,1.666667,24.000000,NaN,NaN,7.833333,...,1.750000,18.166667,2.400000,31.666667,9.000000,68.640259,-149.642453,2021,"{TOOL_003.basePlot.div.31.1.1, TOOL_003.basePl...",NEON
36_2021_NEON,NaN,74.500000,10.500000,1.000000,NaN,7.000000,21.833333,NaN,NaN,28.166667,...,13.000000,19.166667,6.666667,16.166667,NaN,68.616771,-149.629336,2021,"{TOOL_004.basePlot.div.40.1.1, TOOL_004.basePl...",NEON
37_2021_NEON,NaN,79.666667,12.500000,1.000000,NaN,NaN,20.500000,NaN,NaN,10.833333,...,18.500000,11.000000,1.400000,11.500000,NaN,68.560151,-149.528516,2021,"{TOOL_005.basePlot.div.40.1.1, TOOL_005.basePl...",NEON
38_2021_NEON,NaN,76.166667,7.500000,3.000000,NaN,NaN,35.833333,NaN,NaN,26.833333,...,14.333333,11.500000,4.250000,18.500000,NaN,68.622125,-149.280183,2021,"{TOOL_006.basePlot.div.40.3.1, TOOL_006.basePl...",NEON
39_2021_NEON,NaN,78.500000,13.333333,2.000000,8.166667,14.000000,9.000000,NaN,NaN,15.833333,...,6.000000,13.000000,4.000000,15.000000,2.000000,68.646121,-149.356504,2021,"{TOOL_007.basePlot.div.32.4.1, TOOL_007.basePl...",NEON
3_2021_NEON,NaN,66.000000,4.833333,NaN,6.500000,NaN,13.666667,NaN,NaN,NaN,...,5.750000,4.600000,18.166667,13.166667,NaN,71.241421,-156.502862,2021,"{BARR_004.basePlot.div.31.1.1, BARR_004.basePl...",NEON
40_2021_NEON,2.000000,80.166667,11.333333,1.000000,3.000000,1.000000,12.333333,NaN,NaN,17.833333,...,3.333333,9.666667,5.666667,6.166667,NaN,68.561239,-149.510264,2021,"{TOOL_008.basePlot.div.41.4.1, TOOL_008.basePl...",NEON
41_2021_NEON,4.000000,77.500000,11.833333,1.000000,NaN,NaN,15.333333,NaN,NaN,22.666667,...,10.833333,12.500000,4.200000,11.666667,NaN,68.627442,-149.324265,2021,"{TOOL_009.basePlot.div.32.2.1, TOOL_009.basePl...",NEON
42_2021_NEON,NaN,77.666667,14.000000,NaN,2.000000,NaN,23.500000,NaN,NaN,29.166667,...,8.000000,13.333333,9.833333,9.333333,NaN,68.594323,-149.548583,2021,"{TOOL_010.basePlot.div.32.4.1, TOOL_010.basePl...",NEON
43_2021_NEON,3.333333,11.166667,19.500000,NaN,1.000000,NaN,2.000000,NaN,NaN,4.666667,...,3.666667,39.666667,NaN,57.166667,11.500000,68.625975,-149.591294,2021,"{TOOL_011.basePlot.div.41.4.1, TOOL_011.basePl...",NEON
44_2021_NEON,13.000000,64.833333,8.500000,1.333333,8.000000,9.666667,17.333333,NaN,NaN,29.166667,...,15.400000,9.833333,19.000000,11.166667,NaN,68.666664,-149.369751,2021,"{TOOL_041.basePlot.div.40.1.1, TOOL_041.basePl...",NEON
45_2021_NEON,NaN,81.500000,9.833333,NaN,NaN,NaN,12.166667,NaN,NaN,29.833333,...,17.666667,21.166667,5.000000,13.000000,NaN,68.664073,-149.381290,2021,"{TOOL_042.basePlot.div.40.1.1, TOOL_042.basePl...",NEON
46_2021_NEON,NaN,82.333333,22.833333,1.000000,NaN,NaN,12.000000,NaN,NaN,27.666667,...,28.000000,21.000000,3.200000,9.000000,NaN,68.665514,-149.375517,2021,"{TOOL_043.basePlot.div.40.1.1, TOOL_043.basePl...",NEON
4_2021_NEON,NaN,85.166667,7.000000,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,...,6.666667,6.666667,6.400000,16.000000,NaN,71.242585,-156.311974,2021,"{BARR_005.basePlot.div.41.4.1, BARR_005.basePl...",NEON
5_2021_NEON,30.000000,15.750000,36.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,26.000000,1.000000,18.000000,23.400000,71.258085,-156.602068,2021,"{BARR_006.basePlot.div.40.3.1, BARR_006.basePl...",NEON
6_2021_NEON,NaN,90.166667,8.666667,NaN,NaN,NaN,11.500000,NaN,NaN,NaN,...,NaN,9.400000,4.400000,14.833333,1.500000,71.259635,-156.495514,2021,"{BARR_007.basePlot.div.32.4.1, BARR_007.basePl...",NEON
7_2021_NEON,NaN,66.000000,6.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.400000,8.500000,38.600000,24.000000,71.251800,-156.451273,2021,"{BARR_008.basePlot.div.40.1.1, BARR_008.basePl...",NEON
8_2021_NEON,NaN,65.666667,16.400000,NaN,14.333333,NaN,NaN,NaN,NaN,NaN,...,6.400000,5.800000,6.000000,21.200000,NaN,71.289223,-156.618328,2021,"{BARR_009.basePlot.div.31.1.1, BARR_009.basePl...",NEON
9_2021_NEON,NaN,95.666667,4.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.666667,5.666667,3.000000,7.000000,5.000000,71.303030,-156.623333,2021,"{BARR_011.basePlot.div.41.4.1, BARR_011.basePl...",NEON

In [76]:
p = '/mnt/poseidon/remotesensing/arctic/data/training/Test_04/original_files/'
f = 'NEON_PARENT_fcover_total_merged.csv'
parent_plots.to_csv(p + f)

## Map child and parent plots

In [77]:
p = '/mnt/poseidon/remotesensing/arctic/data/vectors/supplementary/tundra_alaska/'
f = 'tundra_alaska.shp'
ak_tundra = gpd.read_file(p + f)

In [78]:
fc = gee.geopandas_to_ee(ak_tundra)
pp2 = parent_plots.reset_index()

In [79]:
par_geom = pp2[['latitude', 'longitude']]
par_points = gee.df_to_ee(par_geom, 
                          latitude='latitude', 
                          longitude='longitude')

In [80]:
chi_geom = totcover[['latitude', 'longitude']]
chi_points = gee.df_to_ee(chi_geom,
                          latitude='latitude', 
                          longitude='longitude')

In [81]:
Map = gee.Map()
Map.center_object(fc, 6)
Map.addLayer(fc, {}, 'arctic')
Map.addLayer(chi_points, {}, 'child')
Map.addLayer(par_points, {'color':'red'}, 'parent')
Map

Map(center=[66.56551547720869, -158.1544109640721], controls=(WidgetControl(options=['position', 'transparent_â€¦