In [27]:
import os
import pandas as pd
import glob

In [28]:
# set input vars
UID = 'id'
DIR = '/mnt/poseidon/remotesensing/arctic/data/vectors/Unmixing/randomPts_ndvi_timeseries'

# set output vars
OUT = '/mnt/poseidon/remotesensing/arctic/data/vectors/Unmixing'
NAME = 'randomPts'
DATE = '2019_2020'
BAND = 'ndvi'

In [29]:
# loop through folders in dir and append dataframes
dfs = []
folders = sorted(glob.glob(f'{DIR}/*'))
print(folders)
for folder in folders:
    
    # loop through phenology files
    files = sorted(glob.glob(f'{folder}/*.csv'))
    dates = []
    ndvi = []
    ids = []
    
    # save dates, ndvi, ids, & date ranges as separate lists
    for f in files:
        dates.append(pd.read_csv(f, usecols=['date_first']))
        ndvi.append(pd.read_csv(f, usecols=['ndvi']))
        ids.append(pd.read_csv(f, usecols=[unique_id]))
    names = [os.path.basename(x).split('_')[0] for x in files]
    
    # create dataframe
    ndvi_df = pd.concat(ndvi, axis=1)
    ndvi_df.columns = pd.to_datetime(names)
    ndvi_orig = ndvi_df.copy()
    dfs.append(ndvi_orig)
    
alldata = pd.concat(dfs, ignore_index=True)

['/mnt/poseidon/remotesensing/arctic/data/vectors/Unmixing/randomPts_ndvi_timeseries/190602', '/mnt/poseidon/remotesensing/arctic/data/vectors/Unmixing/randomPts_ndvi_timeseries/190603', '/mnt/poseidon/remotesensing/arctic/data/vectors/Unmixing/randomPts_ndvi_timeseries/190604']

In [30]:
alldata

,2019-01-01,2019-01-16,2019-01-31,2019-02-15,2019-03-02,2019-03-17,2019-04-01,2019-04-16,2019-05-01,2019-05-16,...,2020-07-29,2020-08-13,2020-08-28,2020-09-12,2020-09-27,2020-10-12,2020-10-27,2020-11-11,2020-11-26,2020-12-11
0,NaN,NaN,NaN,0.009610,0.001309,-0.004962,-0.010213,-0.015566,-0.040396,-0.033394,...,0.369055,0.441325,0.435823,0.012298,NaN,0.022744,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,0.024228,-0.020768,-0.026188,-0.017498,-0.005884,-0.065152,-0.050581,...,0.163701,0.465670,NaN,0.460270,0.034764,0.030869,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,0.007634,NaN,0.012567,-0.011047,-0.003774,0.125396,0.457099,...,0.630048,0.558768,0.320405,0.393334,0.172287,0.029965,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,0.016598,-0.003769,-0.013170,-0.012652,-0.009870,-0.048001,NaN,...,0.341089,0.489583,0.178151,0.255780,0.074736,0.042668,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,-0.014975,-0.014826,-0.018057,-0.022493,-0.006656,-0.031834,-0.102710,...,-0.332932,-0.065099,0.114053,-0.793651,-0.001058,0.025492,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,NaN,NaN,NaN,-0.040150,-0.010998,-0.025780,-0.019821,-0.010963,-0.048143,0.340705,...,0.592979,0.263720,0.452046,-0.032206,0.004651,-0.035345,NaN,NaN,NaN,NaN
449,NaN,NaN,NaN,0.031622,0.004898,-0.022976,0.015614,0.017631,0.444056,0.510354,...,0.360395,0.558037,0.272735,0.542939,0.324060,0.231319,NaN,NaN,NaN,NaN
450,NaN,NaN,NaN,0.010154,-0.010291,-0.011811,-0.001653,-0.011301,-0.047268,0.395653,...,0.693881,0.488487,0.492932,0.562218,0.018783,0.039132,NaN,NaN,NaN,NaN
451,NaN,NaN,NaN,0.024492,0.000215,-0.017322,-0.019084,-0.021262,-0.038027,-0.025018,...,0.414650,0.446843,0.178167,0.394597,-0.014981,-0.005872,NaN,NaN,NaN,NaN
452,NaN,NaN,NaN,0.024885,-0.000466,-0.013312,-0.007867,-0.010897,-0.045296,0.368428,...,0.682292,0.576240,0.307064,0.590900,-0.002967,0.004212,NaN,NaN,NaN,NaN

In [31]:
alldata.to_csv(f'{OUT}/{NAME}_{BAND}_timeseries_{DATE}.csv')